/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Filter: typeof import('./src/components/LogFilter/components/filter.vue')['default']
    LogFilter: typeof import('./src/components/LogFilter/index.vue')['default']
    Native: typeof import('./src/components/LogFilter/components/native.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/index.vue')['default']
    PlaygroundLayoutWrapper: typeof import('./src/components/playground-layout-wrapper/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
