/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    BaseEditor: typeof import('./src/components/code-editor/src/base-editor.vue')['default']
    EnvironmentalChoice: typeof import('./src/components/environmental-choice/index.vue')['default']
    Filter: typeof import('./src/components/LogFilter/components/filter.vue')['default']
    LogFilter: typeof import('./src/components/LogFilter/index.vue')['default']
    Native: typeof import('./src/components/LogFilter/components/native.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/index.vue')['default']
    NodeEditor: typeof import('./src/components/code-editor/src/node-editor.vue')['default']
    PlaygroundLayoutWrapper: typeof import('./src/components/playground-layout-wrapper/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDrawer: typeof import('./src/components/setting-drawer/index.vue')['default']
    WEasyTabs: typeof import('./src/components/w-easy-tabs/index.vue')['default']
  }
}
